export const CardData = [
  {
    title: 'Movies/Series',
    icon: 'https://cdn-icons-png.flaticon.com/128/408/408477.png',
    favourite: false,
    color: 'rgba(22, 204, 240, 1)',
    description:
      'Try acting out the plot or a popular scene without giving away the title of the movie',
    cards: [
      ' Deadpool ',
      'The mask ',
      'The Batman ',
      'Man of steel ',
      'IT',
      ' Annabelle',
      ' Aki & Paw Paw ',
      'Hulk ',
      'Supernatural ',
      'The originals ',
      'Teen wolf',
      'Smallville',
      'HIMYM',
      'Friends',
      'Big Bang theory',
      'Mortal Kombat',
      'Igodo',
      'Confusion Na Wa',
      'King of Boys',
      'Living in Bondage',
      'The Bling Lagosians',
      'Isoken',
      'The Figurine',
      'Rattle Snake',
      'Lionheart',
      'Living in Bondage',
      'Spider-Man No way Home',
      'Raya The Last Dragon',
      'A Quiet Place',
      'The Suicide Squad',
      'Shang Chi and the legend of the ten rings',
      'Luca',
      'Coco',
      'Finding Nemo',
      'Money Heist',
      'Squid Game',
      '365 Days',
      'Stanger Things',
      'Bridgerton',
      'Lucifer',
      'All of us Are Dead The Walking Dead',
    ],
  },
  {
    title: 'Music',
    icon: 'https://cdn-icons-png.flaticon.com/128/2995/2995101.png',
    favourite: false,
    color: 'rgba(243, 133, 156, 1)',
    description:
      'Sing or hum the song but avoid using the song title when singing out',
    cards: [
      'Fall- Davido',
      'Aye- Davido',
      'Mood- wizkid ft Buju',
      'Shoki - Lil kesh',
      'Skelewu- Davido',
      'Issagoal - Naira Marley',
      'Essence - Wizkid ft Tems',
      'Dorobucci- Mavins',
      'Loyalty- Ajebo Hustlers',
      'Dumebi - Rema',
      'Woman - Rema',
      ' Ginger me -Rema',
      ' Finesse - Drake',
      'Kweku the Traveller- Black Sheriff',
      'If- Davido',
      'Damn- Omah Lay',
      'Caro- LAX & Wizkid',
      'Danger- P-square',
      'One Dance- Drake',
      'Hotline Bling -Drake',
      'Gods Plan-  Drake',
      'Toosie Slide- Darke',
      ' In my feelings- Drake',
      ' Loyal- Chris Brown',
      ' Look at me now- Chris Brown',
      'Blow my mind- Davido ft Chris brown',
      'Venom- Eminem ',
      'Cold Outside - Timaya',
      'The real slim shady-  Eminem',
      ' Without me - Hasley',
      'Rap God - Eminem',
      'Godzilla- Eminem',
      'No role modelz - J.Cole',
      'Middle Child - J. Cole',
      'Terminator - Asake',
      'Rush - Ayra Starr',
      'KU LO SA - Oxlade',
      'It’s plenty - Burna Boy',
      'Call of duty - Zinoleesky',
      'Electricity - Davido',
      'Joha - Asake',
      'Soweto - Victony',
      'Bandana - Fireboy',
      'Bloody Samaritan - Ayra Starr',
      'Peace be Unto You - Asake',
      'Certified Loner - Mayokun',
      'Organise - Asake',
      'Watawi - Ckay',
      'Bad to me - Wizkid',
      'Kolomental - Victony',
    ],
  },
  {
    title: 'Act it Out',
    icon: 'https://cdn-icons-png.flaticon.com/128/1773/1773621.png',
    favourite: false,
    color: '#002741',
    description:
      'Act or Describe the word without using words or humming, only body movements.',
    cards: [
      'Cycling',
      'Watching TV',
      'Swimming',
      'Running',
      'Flying in a plane',
      'Sleeping',
      'Flipping plantain',
      'Listening to music',
      'Driving a car',
      'Nigerian Mother',
      'Keke Driver',
      'Writing a letter',
      'Giving a haircut',
      'Drinking',
      'Typing',
      'Eating',
      'SS3 Student',
      'Playing the guitar',
      'Drumming',
      'Yawning',
      'Playing golf',
      'Praying',
      'Brushing teeth',
      'Showering',
      'Meditating',
      'Singing',
      'Protesting',
      'Arguing',
      'New Comer',
      'Okada man',
      'Bus Conductor',
      'Sweeping the floor',
      'Washing plates',
      'Washing Car',
      'Getting Married',
      'Playing drums',
      'Hacking',
      'Carrying weight',
      'Fetching water',
      'Hawking things',
      'Mopping the floor',
      'Killing Mosquito',
      'Frying fish',
      'Throwing away things',
      'Shy',
      'Pulling something',
      'Writing a book',
      'Taking & Posting Pictures',
      'Petting A Dog',
      'Digging a pit',
      'Fighting with a goat.Cycling a tricycle',
      'Watching a Romantic Comedy',
      'Collecting Breakfast',
      'Doing assignment',
      'Begging Lecturer',
      'Cheating in Exam',
      'Carrying weight',
      'Proposing to a girl',
      'Texting with your babe',
      'Cooking meat',
      'Listening to Naira Marley',
      'Driving in Traffic',
      'Writing a love letter ',
      'Buying food',
      'Flying a drone',
      'Winning an award',
      'Acting on stage',
      'Pretending to be surprised',
      'Wrestling',
      'Watching YouTube',
      'Teaching a language',
      'Having a bath',
      'Learning',
      'On Okada',
      'Putting on a wig',
      'Pushing a wheel barrow',
      'Toasting a girl',
      'Like a tout',
      'Hacking a Computer',
      'Pricing in the Market',
      'Cutting Grass',
      'Hyping a friend',
      'Making indomie',
      'Sleeping',
      'Giving Birth',
      'Conducting Surgey',
      'Shouting at a mad man',
      'Pounding Dough',
      'Pounding Yam',
      'Chopping Breakfast (Heartbreak)',
      'Campaigning for election',
      'Passenger on Okada',
      'Chopping food with knife',
      'Stalking Someone',
      'Charging phone and texting',
      'Taking Injection',
      'Giving Injection',
      'Climbing a tree',
      'Trimming a Garden',
    ],
  },
  {
    title: 'Popular Personalities',
    icon: 'https://cdn-icons-png.flaticon.com/128/5175/5175889.png',
    favourite: false,
    color: 'rgba(133, 141, 243, 1)',
    description:
      'Make use of popular phrases or actions used by these celebrities and try not to spill out their names in the process.',
    cards: [
      'Ramsey Noah',
      'Yul Edochie',
      ' Richard Mofe Damijo (RMD)',
      'Aki',
      ' Paw Paw',
      'Kanyo O Kanyo',
      ' Osuofia',
      'Rita Dominic',
      'Tonto Dikeh',
      'Mercy Johnson',
      'Tinubu',
      'Genevieve Nnaji',
      'Funke Akindele',
      'Bobrisky',
      'Mama G',
      'Sydney Talker',
      'Craze Clown',
      'Sabnius',
      'Basket Mouth',
      'Speed Darlington',
      'Josh2Funny',
      'Mark Angel',
      'Broda Shaggi',
      'Taaoma',
      'Helen Paul',
      'Wizkid',
      'Davido',
      'Buju',
      '2baba',
      'Timaya',
      'Omah Lay',
      'Fireboy',
      'MI',
      'Burna Boy',
      'Naira Marley',
      'Dwanye Johnson',
      'Justin Bieber',
      'Johnny Depp',
      'Will Smith',
      'Kim Kardashian',
      'Nicki Minaj',
      'Cardi B',
      'Vin Diesel',
      'Steve harvey',
      'Selena Gomez',
      'Asake',
      'Victony',
      'Oxlade',
      'Patoranking',
      'Rema',
    ],
  },
  // {
  //   title: 'Places',
  //   icon: '',
  //   favourite: false,
  //   color: 'rgba(242, 136, 92, 1)',
  //   description:
  //     'How many places have you been to so far? Describe these popular places without giving away their name',
  // },
  {
    title: 'Food',
    icon: 'https://cdn-icons-png.flaticon.com/128/1037/1037855.png',
    favourite: false,
    color: 'rgba(250, 225, 91, 1)',
    description:
      'Hmmm, yummy. Everyone loves food, try your luck at describing these meals without saying the actual name.',
    cards: [
      'Jollof Rice',
      'Pounded Yam',
      'Amala & Ewedu',
      'Ogbono',
      'Puff Puff',
      'Akara',
      'Pepper Soup',
      'Suya',
      'Yam Porridge',
      'Egusi',
      'Eba',
      'Chin Chin',
      'Boli (Roasted Plantain)',
      'Beans & Dodo',
      'Okra Soup',
      'Moi Moi',
      'Bread (Agege)',
      'Abacha',
      'Afang Soup',
      'Pap',
      'Asun',
      'Banga Soup',
      'Fufu',
      'Ofada',
      'Potato Chips',
      'Ice Cream',
      'Pizza',
      'Fried Chicken',
      'Okpa',
      'Spaghetti',
      'Indomie',
      'Fried Yam',
      'Garri & Groudnut',
      'Grilled Fish',
      'Agbalumo',
      'Banana',
      'Mango',
      'Orange',
      'Strawberry',
      'Cashew',
      'Garden Egg',
      'Grapes',
      'Apple',
      'Cabin Biscuit',
      'Carrot',
      'Cucumber',
      'Watermelon',
      'Onions',
      'Cabbage',
      'lemons',
    ],
  },
  {
    title: 'Animals',
    icon: 'https://cdn-icons-png.flaticon.com/128/3426/3426229.png',
    favourite: false,
    color: '#588CB5',
    description:
      'How many animals can you list from A to Z, try describing these animals and see who knows them best, Try not to spill the name in the process.',
    cards: [
      'Elephant',
      'Lion',
      'Lizard',
      'Fowl',
      'Cow',
      'Goat',
      'Snail',
      'Tiger',
      'Caterpillar',
      'Squirrel',
      'Rat',
      'Snake',
      'Tortoise',
      'Turtle',
      'Horse',
      'Donkey',
      'Cats',
      'Dogs',
      'Fish',
      'Kangaroo',
      'Lemur',
      'Leopard',
      'Llama',
      'Lobster',
      'Giraffe',
      'Monitor lizard',
      'Monkey',
      'Moose',
      'Flamingo',
      'Duck',
      'Gorilla',
      'Guinea Pig',
      'Dinosaur',
      'Bat',
      'Bear',
      'Wolf',
      'Cat',
      'Raccon',
      'Red Fox',
      'Blue Whale',
      'Weasel',
      'Beaver',
      'Deer',
      'Hedgehog',
      'Polar bear',
      'Seal',
      'Cougar',
      'Platypus',
    ],
  },

  {
    title: 'Anime & Manga',
    icon: 'https://cdn-icons-png.flaticon.com/128/2281/2281829.png',
    favourite: false,
    color: 'rgba(252, 101, 101, 1)',
    description:
      "So you think you're a weeb? Well, prove it!, act out these anime or manga characters without giving out their names.",
    cards: [
      ' Naruto',
      'Bleach',
      'JJK',
      'One piece',
      'One punch man',
      'Dragon Ball Z',
      'My Hero ACADEMIA',
      'Black clover',
      'Fullmetal alchemist',
      'Scissor Seven',
      'Seven Deadly Sins',
      'High School DXD',
      'Bastard',
      'Castlevania',
      'Tokoyo ghoul',
      'Fullmetal alchemist',
      'Baki',
      'Attack on Titans',
      'Fate Series',
      'Hunter X Hunter',
      'Jojo Bizzarre',
      'Demon Slayer',
      'Fire Force',
      'Avater: The Last Airbender',
      'Death Note: Desu nôto',
      'Mononoke',
      'Purinsesu Chuchu',
      'Rainbow: Nishakubou no shichinin',
      'Taiyô no ko Esuteban',
      'Sayonara zetsubô sensei',
      'Akage no An',
      'Kabaneri of the iron fortress',
      'Steins Gate',
      'Gintama',
      'Itachi',
      'Sasuke',
      'Konohagakure',
      'Bankai',
      'Gojo Satoru',
      'Domain Expansion',
      'Ichigo Kurusaki',
      'Aizen',
      'Rorona Zoro',
      'Monkey D Luffy',
      'Hinata Shoyo',
      'Kurama',
      'Uchiha Madara',
      'Pain',
      'Anya',
      'Meliodias',
    ],
  },
  {
    title: 'Accents & Impressions',
    icon: 'https://cdn-icons-png.flaticon.com/128/1773/1773572.png',
    favourite: false,
    color: '#1A2A36',
    description:
      'How good are you at impersonations and accents ? Lets find out',
    cards: [
      'Quagmire',
      'Peter Griffen',
      'Batman',
      'Terminator',
      'Kelvin Hart',
      'John Cena',
      'The Rock',
      'Bugs Bunny',
      'Donald Duck',
      'Thanos',
      'Donald trump',
      'Trevor Noah',
      'Mickey Mouse',
      'Barrack Obama',
      'Morgan Freeman',
      'Rick Sanchez',
      'Super Mario',
      'Sponge Bob',
      'Michael Jackson',
      'Dark Vader',
      'Goofy(Mickey Mouse)',
      'Stewie Griffin',
      'Optimus Prime',
      'Winne the Pooh',
      'The Joker',
      'Homer Simpson',
      'American',
      'Black American',
      'British',
      'Ontisha main-market seller',
      'Yoruba Demon',
      'Hausa shoemaker',
      'scottish',
      'Italian mob boss',
      'Yul Edochie',
      'Chinese',
      'Ghanaian',
      'French',
      'German',
      'Jamaican',
      'Russian',
      'South African',
      'Lagos abgero',
      'Mexican',
      'Canadian',
      'Pete Edochie',
      'anime character',
      'K-drama character',
      'Australian',
      'Kanaya O Kanaya',
    ],
  },
  {
    title: 'Nollywood',
    icon: 'https://cdn-icons-png.flaticon.com/128/409/409616.png',
    favourite: false,
    color: 'rgba(255, 157, 157, 1)',
    description:
      'We all miss old Nollywood , act out your favourite actor/actress',
    cards: [
      'Mercy Johnson',
      'RMD',
      'Ramsey Nouah',
      'Yul Edochie',
      'Genevieve Nnaji',
      'Jim Iyke',
      'Aki',
      'Rachael Oniga',
      'Pete Edochie',
      'Cynthia Okereke',
      'Odunlade adekola',
      'Funke Akindele',
      'Desmond Elliot',
      'Paw Paw',
      'Rita Dominic',
      'Ini Edo',
      'Destiny Etiko',
      'Mercy Aigbe',
      'Nancy Isime',
      'Zack Orji',
      'Mr Ibu',
      'Mike Ezuruonye',
      'Omotala Jalade',
      'Alex Ekubo',
      'Chiwetalu Agu',
      'Uzor Arukwe',
      'Ada Ameh',
      'Adesuwa Etomi',
      'Kate Henshaw',
      'Beverly Naya',
      'Yvonne Orji',
      'Sharon Ooja',
      'Helen Paul',
      'Kate Henshaw',
      'Regina Daniels',
      'Mama Gee',
      'Tonto Dikeh',
      'Joke Sliva',
      'Sola Sobowale',
      'Chacha Eke',
      'Kanayo O. Kanayo',
      'Sam Dede',
      'Zubby Michael',
      'Efa Iwara',
      'Olu Jacobs',
      'Bovi',
      'Osita Iheme',
      'Okey Bakassi',
      'Segun Arinze',
      'Belinda Effah',
    ],
  },
  // {
  //   title: 'Folktales',
  //   icon: '',
  //   favourite: false,
  //   color: 'rgba(255, 163, 83, 1)',
  //   description: '',
  // },
  {
    title: 'Occupation',
    icon: 'https://cdn-icons-png.flaticon.com/128/1839/1839325.png',
    favourite: false,
    color: 'rgba(255, 111, 82, 1)',
    description:
      'What would you like to be when you grow up, a baller? Act out these occupations and see how many you can get in a round.',
    cards: [
      'Lawyer',
      'Doctor',
      'Conductor',
      'Driver',
      'Ashewo',
      'Tech bro',
      'Chef',
      'House boy',
      'Dentist',
      'Pharmacist',
      'Veterinarian',
      'Civil Engineer',
      'Brick layer',
      'Teacher',
      'Accountant',
      'Nanny',
      'Waste packer',
      'Cleaner',
      'Gadget Engineer',
      'Real Estate Agent',
      'Mechanic',
      'Bus Driver',
      'Plumber',
      'Painter',
      'Graphic Designer',
      'Receptionist',
      'Architect',
      'Electrician',
      'Tailor',
      'Carpenter',
      'Brand Inflencer',
      'Surgeon',
      'Pilot',
      'Astronaut',
      'Pre-school teacher',
      'Hairdresser',
      'Make up artist',
      'School Counselor',
      'Architect',
      'Cement Mason',
      'Sports Coach',
      'Mattress tester',
      'Janitor',
      'Security Guard',
      'TrucK driver',
      'House help',
      'Receptionist',
      'Personal Assistant',
      'Customer Service Rep',
      'Police Officer',
    ],
  },
  {
    title: 'Heroes & Villains',
    icon: 'https://cdn-icons-png.flaticon.com/128/1477/1477218.png',
    favourite: false,
    color: 'rgba(104, 118, 255, 1)',
    description: 'Good vs Bad. act out your favourite heroes and villains',
    cards: [
      'Superman',
      'Batman',
      'Captain America',
      'Iron Man',
      'The Flash',
      'Wonder Woman',
      'Green Lantern',
      'Aqua Man',
      'Spider-Man',
      'Captain Marvel',
      'Black Partner',
      'The Hulk',
      'Robin',
      'Silver Surfer',
      'Professor X',
      'Cyclops',
      'Thor',
      'Ant-Man',
      'Scarlett Witch',
      'Hawkeye',
      'Green Arrow',
      'Rocket Raccoon',
      ' Cat Woman',
      'Cyborg',
      ' Homelander',
      'Sandman',
      'Darkseid',
      'The Joker',
      'Thanos',
      'Green Golbin',
      'Death stroke',
      'Reverse Flash',
      'Doctor Doom',
      'Magneto',
      'Doctor Octopus',
      'The Deep',
      'Galactus',
      'Lex Luthor',
      'Scorpion',
      'Sinestro',
      'Harley Quinn',
      'Mr Freeze',
      'Posion Ivy',
      'Black Adam',
      'Kano',
      'Shang Tsung',
      'Goro',
      'Reptile',
      'Kabal',
      'Mileena',
    ],
  },
  {
    title: 'Cartoons',
    icon: 'https://img.icons8.com/color/2x/cartoon_network.png',
    favourite: false,
    color: 'rgba(129, 210, 255, 1)',
    description:
      'From Cartoon Network to Boomerang, can you act out all your favorite cartoons without giving out their names?',
    cards: [
      'Ben 10',
      'Sponge Bob',
      'Batman: The Animated Series',
      'Samurai Jack',
      'Avatar: The Last Airbender',
      'Total Drama Island',
      'Scooby-Doo! Mystery Incorporated',
      'Justice League',
      'The Avengers: Earths Mightiest Heroes',
      'Batman Beyond',
      'Teenage Mutant Ninja Turtles',
      'Teen Titans',
      'Ben 10',
      'Generator Rex',
      'Trollhunters',
      'Gargoyles',
      'Roswell Conspiracies: Aliens',
      ' Myths & Legends',
      'The Legend of Korra',
      'Voltron: Legendary Defender',
      'The Spectacular Spider-Man',
      'Megas XLR',
      'Sym-Bionic Titan',
      'Gravity Falls',
      'Star Wars: The Clone Wars',
      'Star Wars: Rebels',
      'Kim Possible',
      'Codename: Kids Next Door',
      'Danny Phantom',
      'The Dragon Prince',
      'Futurama',
      'Tangled: The Series',
      '3Below: Tales of Arcadia',
      'Castlevania',
      'Rick and Morty',
      'Dawn of the croods',
      'Big Mouth',
      'Love',
      ' Death Robots',
      'Inside job',
      'Bojack Horseman',
      'Arcane',
      'Archer',
      'American Dad',
      'South Park',
      'Adventure time',
      'Bod Burgers',
      'Dexters Laboratory',
      'X-men',
      'Courage the Cowardly Dog',
      'The Powerpuff Girls',
      'The Simpsons',
    ],
  },
  {
    title: 'Sports',
    icon: 'https://cdn-icons-png.flaticon.com/128/2112/2112215.png',
    favourite: false,
    color: '#B4B4B9',
    description:
      'What fan club do you belong to? try describing these sports and teams, let’s see if you a true fan or sportsman.',
    cards: [
      'Sports',
      'Skipping Rope',
      'Discus',
      'Running',
      'Javalin',
      'Football',
      'Basketball',
      'Volleyball',
      'Lawn Tennis',
      'Table Tennis',
      'Swimming',
      'Polo',
      'Archery',
      'Boxing',
      'Badminton',
      'Judo',
      'Wrestling',
      'Bowling',
      'Hockey',
      'Cricket',
      'Golf',
      'Weight Lifting',
      'Gymnastics',
      'Horse racing',
      'Car Racing',
      'Bike Racing',
      'Cycling',
      'Handball',
      'Rugby',
      ' Kick Boxing',
      ' Marathon',
      ' Hammer Throw',
      'Pole vault',
      'High Jump',
      'Sack racing',
      'First to School',
      'Real Madrid',
      'Barcelona',
      'Manchester United',
      'Juventus',
      ' Chelsea',
      'Paris Saint German',
      'Bayern Munich',
      'Arsenal',
      'Liverpool',
      'Manchester City',
      'Borussia Dortmund',
      'Bourne Mouth',
      'Super Eagles',
      'Inter millan',
      'Ac Millian',
    ],
  },
  {
    title: 'Brands',
    icon: 'https://cdn-icons-png.flaticon.com/128/8977/8977249.png',
    favourite: false,
    color: '#028AFB',
    description: 'Do you know all the popular brands ?',
    cards: [
      'Oxford Biscuit',
      'Kuda Bank',
      'Dano Milk',
      'Peak Milk',
      'Apple',
      'Tecno',
      'GT Bank',
      'UBA',
      'Airtel',
      'MTN',
      'GLO',
      '9Mobile',
      'Samsung',
      'Louis Vuitton',
      'Dolce & Gabanna',
      'Nike',
      'Panadol',
      'Indomie',
      'Zenith Bank',
      'Dangote',
      'Google',
      '2go',
      'Access Bank',
      'Chipper',
      'Airel',
      'Wawu Soap',
      'Flutterwave',
      'Paystack',
      'Shoprite',
      'Chicken Republic',
      'KFC',
      'Dodo Pizza',
      'Dominos Pizza',
      'Dettol',
      'Omo',
      'Apple',
      'Google',
      'Amazon',
      'Microsoft',
      'Facebook',
      'Burger King',
      ' Coca-cola',
      ' Chanel',
      'Fenty Beauty',
      'House of Tara',
      'Aliexpress',
      'Jumia',
      'Mr Biggs',
      'Play Station',
      'X Box',
    ],
  },
  {
    title: 'Games',
    icon: 'https://cdn-icons-png.flaticon.com/128/7231/7231265.png',
    favourite: false,
    color: '#2F4B60',
    description: 'Try to guess these popular games we played as children',
    cards: [
      'After Round Wan',
      'Tinko Tinko',
      'Cinderella went to see a fellow',
      'Mr. Macaroni',
      'Hide and Seek',
      'Catcher (Boju - Boju)',
      'Musical Chairs',
      'Ten ten',
      'Suwe',
      'Who is Garden',
      'I Call On',
      'Who stole the meat from the cooking pot',
      'When will you marry',
      'Chess',
      'Scrabble',
      'Monopoly',
      'Draft',
      'Checkers',
      'Whot (Cards)',
      'Ncho (Ayo)',
      'Ludo',
      'Snake and Ladder',
      'Snake Rope',
      'Prince Of Persia',
      'Candy Crush',
      'Pac Man',
      'Angry Bird',
      'Jet pack Joy ride',
      'Pac Man',
      'Tetris',
      'Temple Run',
      'Subway Surfers',
      'Clash Clans',
      'Mario',
      'Grand Theft Auto',
      'Mine Craft',
      'Assassin’s Creed',
      'Apex Legends',
      'League of legends',
      'Fornite',
      'Red Dead redemption',
      'Fall Guys',
      'Call of Duty',
      'Talking Tom',
      'Among Us',
      'Final Fantasy',
      'Elden rings',
      'Cross Fire',
      'Pubg',
      'Roblox',
    ],
  },
];
