export const CardData = [
  {
    title: 'Movies/Series',
    icon: '',
    favourite: false,
    color: 'rgba(22, 204, 240, 1)',
  },
  {
    title: 'Music',
    icon: '',
    favourite: false,
    color: 'rgba(243, 133, 156, 1)',
  },
  {
    title: 'Artists/Celebs',
    icon: '',
    favourite: false,
    color: 'rgba(133, 141, 243, 1)',
  },
  {
    title: 'Places',
    icon: '',
    favourite: false,
    color: 'rgba(242, 136, 92, 1)',
  },
  {
    title: 'Food',
    icon: '',
    favourite: false,
    color: 'rgba(250, 225, 91, 1)',
  },
  {
    title: 'Animals',
    icon: '',
    favourite: false,
    color: 'rgba(154, 80, 242, 1)',
  },
  {
    title: 'Politics',
    icon: '',
    favourite: false,
    color: 'rgba(115, 255, 247, 1)',
  },
  {
    title: 'Anime & Manga',
    icon: '',
    favourite: false,
    color: 'rgba(252, 101, 101, 1)',
  },
  {
    title: 'School Life',
    icon: '',
    favourite: false,
    color: 'rgba(115, 255, 129, 1)',
  },
  {
    title: 'Holidays',
    icon: '',
    favourite: false,
    color: 'rgba(255, 157, 157, 1)',
  },
  {
    title: 'Folktales',
    icon: '',
    favourite: false,
    color: 'rgba(255, 163, 83, 1)',
  },
  {
    title: 'Occupation',
    icon: '',
    favourite: false,
    color: 'rgba(255, 111, 82, 1)',
  },
  {
    title: 'Companies',
    icon: '',
    favourite: false,
    color: 'rgba(255, 175, 64, 1)',
  },
  {
    title: 'Punishment',
    icon: '',
    favourite: false,
    color: 'rgba(104, 118, 255, 1)',
  },
  {
    title: 'Cartoons',
    icon: '',
    favourite: false,
    color: 'rgba(129, 210, 255, 1)',
  },
  {
    title: 'Act it Out',
    icon: '',
    favourite: false,
    color: 'rgba(207, 127, 255, 1)',
  },
  {
    title: 'Sports',
    icon: '',
    favourite: false,
    color: 'rgba(106, 201, 255, 1)',
  },
];
